modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"

[[mods]]
modId="personalspace"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_display_url}"
logoFile="personalspace.png"
credits="Original Personal Space mod by the original authors/contributors. Unofficial NeoForge 1.21.1 port by Crazerium."
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.personalspace]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.personalspace]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.personalspace]]
modId="infiniverse"
type="required"
versionRange="[1.21-2.0.1.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config = "personalspace.mixins.json"